PersonalBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
	path('', views.index, name = 'index'),
	path('registration/', views.registrationUser, name = 'registrationUser'),
	path('login/', views.loginUser, name = 'loginUser'),
	path('logoutUser/', views.logoutUser, name = 'logoutUser'),
	path('<int:user_id>/', views.viewProfile, name = 'viewProfile'),
	path('<int:user_id>/<int:post_id>/', views.viewPost, name = 'viewPost'),
	path('<int:user_id>/<int:post_id>/leave_comment/', views.leave_comment, name = 'leave_comment'),
	path('createPost/', views.createPost, name = 'createPost'),
	]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
	post_title = models.CharField('заголовок вопроса', max_length=50)
	post_text = models.TextField('текст вопроса')
	pub_date = models.DateTimeField('дата публикации')
	author_first_name = models.CharField('имя', max_length=50)
	author_last_name = models.CharField('фамилия', max_length=50)
	user = models.ForeignKey(User, on_delete=models.CASCADE)

	class Meta:
		verbose_name = 'Пост'
		verbose_name_plural = 'Посты'

class Comment(models.Model):
	author_first_name = models.CharField('имя', max_length=50)
	author_last_name = models.CharField('фамилия', max_length=50)
	comment_text = models.CharField('текст комментария', max_length = 200)
	post = models.ForeignKey(Post, on_delete = models.CASCADE)

	class Meta:
		verbose_name = 'Ответ'
		verbose_name_plural = 'Ответы'

class AdminInformation(models.Model):
	text_information = models.CharField('текст информации', max_length=50)

	class Meta:
		verbose_name = 'Информация админа'
		verbose_name_plural = 'Информация админа'

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Post
  
class RegistrationForm(UserCreationForm):
	username = forms.CharField(max_length=20, label='логин')
	first_name = forms.CharField(max_length=32, label='имя')
	last_name=forms.CharField(max_length=32, label='фамилия')
	email=forms.EmailField(max_length=64, label='почта')
	password1=forms.CharField(widget=forms.PasswordInput(), label='пароль')
	password2=forms.CharField(widget=forms.PasswordInput(), label='повторите пароль')

	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
		labels = {
    		'username': 'логин',
    		'first_name': 'Имя',
    		'last_name': 'Фамилия',
    		'email': 'Почта',
    		'password1': 'пароль',
    		'password2': 'подтверждение пароля',
    	}

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(max_length=20, label='логин')
    password = forms.CharField(widget=forms.PasswordInput(), label='пароль')

    class Meta:
    	model = User
    	fields = ['username', 'password']
    	labels = {
    		'username': 'логин',
    		'password': 'пароль',
    	}

class CreatePostForm(forms.ModelForm):
	post_title = forms.CharField(max_length=50, label='заголовок')
	post_text = forms.CharField(max_length=200, label='текст')

	class Meta:
		model = Post
		fields = ('post_title', 'post_text')

blog/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, logout, login as auth_login
from .forms import RegistrationForm, LoginUserForm, CreatePostForm
from .models import Post, Comment, AdminInformation
import datetime

def index(request):
	all_users = User.objects.filter(is_staff = 0)
	all_posts = Post.objects.filter(user = request.user.id).count()
	all_admin_inf = AdminInformation.objects.all()
	return render(request, 'index.html', {'all_users': all_users, 'all_posts': all_posts, 'all_admin_inf':all_admin_inf })

def registrationUser(request):
	all_admin_inf = AdminInformation.objects.all()
	form = RegistrationForm(data=request.POST)
	if form.is_valid():
		form.save()
		return redirect('blog:loginUser')
	else:
		return render(request, 'registration.html', {'form': form, 'all_admin_inf':all_admin_inf})

def loginUser(request):
	all_admin_inf = AdminInformation.objects.all()
	form = LoginUserForm(request=request, data=request.POST)
	if form.is_valid():
		username = form.cleaned_data.get('username')
		password = form.cleaned_data.get('password')
		user = authenticate(username=username, password=password)
		if user is not None:
			auth_login(request, user)
			return redirect('blog:index')
	else:
		return render(request, 'login.html', {'form': form, 'all_admin_inf':all_admin_inf})

def logoutUser(request):
	logout(request)
	return redirect('blog:index')

def viewProfile(request, user_id):
	all_admin_inf = AdminInformation.objects.all()
	user = User.objects.get(id = user_id)
	posts = Post.objects.all().filter(user_id = user_id)
	all_posts = Post.objects.filter(user = request.user.id).count()
	return render(request, 'profile.html', {'user': user, 'posts': posts, 'all_posts': all_posts, 'all_admin_inf':all_admin_inf })

def viewPost(request, user_id, post_id):
	all_admin_inf = AdminInformation.objects.all()
	user = User.objects.get(id = user_id)
	post = Post.objects.get(id = post_id)
	comments = Comment.objects.all().filter(post_id = post_id)
	all_posts = Post.objects.filter(user = request.user.id).count()
	return render(request, 'viewPost.html', {'post': post, 'user': user, 'comments': comments, 'all_posts': all_posts, 'all_admin_inf':all_admin_inf}) 

def createPost(request):
	all_admin_inf = AdminInformation.objects.all()
	form = CreatePostForm(data=request.POST)
	if form.is_valid():
		post_title = form.cleaned_data.get('post_title')
		post_text = form.cleaned_data.get('post_text')
		pub_date = datetime.datetime.now()
		author_first_name = request.user.first_name
		author_last_name = request.user.last_name
		user_id = request.user.id
		Post.objects.create(post_title = post_title, post_text = post_text, pub_date = pub_date, author_first_name = author_first_name, author_last_name = author_last_name, user_id = user_id)
		return HttpResponseRedirect( reverse('blog:viewProfile', args = [request.user.id]))
	else:
		return render(request, 'createPost.html', {'form': form, 'all_admin_inf':all_admin_inf})

def leave_comment(request, user_id, post_id):
	post = Post.objects.get(id = post_id)
	first_name = request.user.first_name
	last_name = request.user.last_name
	post.comment_set.create(author_first_name=first_name, author_last_name=last_name, comment_text = request.POST['text'])
	return HttpResponseRedirect( reverse('blog:viewPost', args=[user_id, post_id]))

PersonalBlog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    <link rel="stylesheet" href="{% static "css/index.css" %}">
    <link rel="stylesheet" href="{% static "css/profile.css" %}">
    <link rel="stylesheet" href="{% static "css/viewPost.css" %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="background" style="background-image: url('{% static "background.jpg"%}')">
        <div class="header">
            <div class="header_block">
                <div class="header_word_block">
                    <span class="header_word">Личный Блог</span>
                </div>
            </div>
        </div>
        <div class="main">
            <div class="main_block">
                <div class="m1">
                    <div class="m1_zag_block">
                        <div class="stats_im" style="background-image: url('{% static "stats.png"%}')"></div>
                        <p>Статистика</p>
                    </div>
                    <div class="m1_stat_block">
                        {% if not request.user.is_authenticated %}
                            <p>Вы должны быть авторизованы, чтобы видеть статистику!</p>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                        <div>
                            <p>Кол-во ваших постов: {{all_posts}}</p>
                            <p>Дата регистрации: <br> {{request.user.date_joined}}</p>
                            <p>Почта: {{request.user.email}}</p>
                        </div>
                            
                        {% endif %}
                    </div>
                </div>
                <div class="m2">
                    <div class="block_profile_view">
                        {% if not request.user.is_authenticated %}
                            <a class="button_login" href="{% url 'blog:loginUser' %}">Войти</a>
                            <a class="button_register" href="{% url 'blog:registrationUser' %}">Зарегистрироваться</a>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                            <div class="j1"><p class="name_base">{{request.user.last_name}} {{request.user.first_name}}</p></div>
                            <div class="j2"><a class="name_base_create" href="{% url 'blog:createPost' %}">Создать пост</a></div>
                            <div class="j3"><a class="name_base_profile" href="{% url 'blog:viewProfile' request.user.id %}">Профиль</a></div>
                            <div class="j4"><a class="name_base_leave" href="{% url 'blog:logoutUser' %}">Выйти</a></div>
                        {% endif %}
                    </div>
                    <div class="block_list">
                        <main>
                            {% block content %}{% endblock %}
                        </main>
                    </div>
                </div>
                <div class="m3">
                    <div class="m3_zag_block">
                        <div class="link_im" style="background-image: url('{% static "link.png"%}')"></div>
                        <p>Информация</p>
                    </div>
                    {% for i in all_admin_inf %}
                        <div class="inf_admin_block"><p>{{i.text_information}}</p></div>
                    {% endfor %}

                </div>
            </div>
        </div>      
    </div>
</body>
</html>

PersonalBlog/templates/createPost.html
{% extends 'base.html' %}
 
{% block title %}Создать пост{% endblock %}
 
{% block content %}
    <div class="create_post_head"><h2>Создать пост</h2></div>
    <div class="create_post_c_block">
    	<form method="post">
        	{% csrf_token %}
        	{{ form.as_p }}
        	<button class="authorize_button" type="submit">Отправить</button>
    	</form>
	</div>
{% endblock %}

PersonalBlog/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Личный Блог{% endblock %}
 
{% block content %}
	<div class="index_view_profile_block_top"><p>Список пользователей</p></div>
    {% for a in all_users %}
    	<div class="index_view_profile_block"><div class="person_im" style="background-image: url('{% static "person.png"%}')"></div><div class="index_view_profile_block_name"><a href="{% url 'blog:viewProfile' a.id %}" >{{a.last_name}} {{a.first_name}}</a></div></div>
    {% endfor %}
{% endblock %}

PersonalBlog/templates/login.html
{% extends 'base.html' %}
 
{% block title %}Авторизация{% endblock %}
 
{% block content %}
<div class="authorize_head"><h2>Авторизация</h2></div>
<div class="login_form_block">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="authorize_button" type="submit">Отправить</button>
    </form>
</div>
    
{% endblock %}

PersonalBlog/templates/profile.html
{% extends 'base.html' %}
 
{% block title %}Профиль{% endblock %}
 
{% block content %}
    <div class="profile_back_block"><div class="profile_a"><a href="{% url 'blog:index' %}">На главную</a></div><p>{{user.last_name}} {{user.first_name}}</p></div>
    {% for p in posts %}
    		<a class="profile_view_profile_block" href="{% url 'blog:viewPost' user.id p.id %}">
    			<div class="p1_block"><p class="p1">{{p.post_title}}</p></div>
    			<div class="p2_block"><p class="p2">{{p.pub_date}}</p></div>
    		</a>
    {% endfor %}
{% endblock %}

PersonalBlog/templates/registration.html
{% extends 'base.html' %}
 
{% block title %}Регистрация{% endblock %}
 
{% block content %}
    <div class="registat_head"><h2>Регистрация</h2></div>
    <div class="registr_c_block">
    	<form method="post">
        	{% csrf_token %}
        	{{ form.as_p }}
        	<button class="authorize_button" type="submit">Отправить</button>
    	</form>
	</div>	
{% endblock %}

PersonalBlog/templates/viewPost.html
{% extends 'base.html' %}
 
{% block title %}Профиль{% endblock %}
 
{% block content %}
    <div class="profile_back_block"><div class="profile_a"><a href="{% url 'blog:index' %}">На главную</a></div><p>{{user.last_name}} {{user.first_name}}</p>
    </div>
        <div class="post_block">
            <p class="post1">{{post.post_title}}</p>
            <p>{{post.post_text}}</p>
        </div>
        {% for c in comments %}
            <div class="view_comment_block">
                <p>{{c.author_last_name}} {{c.author_first_name}}</p>
                <p>{{c.comment_text}}</p>
            </div>
        {% endfor %}
        {% if request.user.is_authenticated %}
        <div class="view_leave_block">
            <form action="{% url 'blog:leave_comment' user.id post.id %}" method="POST">
                {% csrf_token %}
                <div class="view_leave_head"><p>Оставьте комментарий</p></div>
                <textarea class="view_leave_textarea" name="text" required="" placeholder="Текст ( не более 200 символов )"></textarea><br>
                <div><button  class="view_leave_button" type="submit">Оставить ответ</button></div>
            </form>
        </div>
        {% endif %}
{% endblock %}